CREATE TABLE "system_config" (
    "id" TEXT PRIMARY KEY DEFAULT 'main',
    "defaultLimit" INTEGER NOT NULL DEFAULT 100,
    "defaultExpiry" INTEGER NOT NULL DEFAULT 365,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "system_config"
  ADD COLUMN "notifyKeyLimit" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN "notifyAccessDenied" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN "notifyWeeklyReport" BOOLEAN NOT NULL DEFAULT FALSE; 